export const CHANGE_VALUE = 'change_value'
export const CLICK_BTN = 'click_btn'
export const DELETE_ITEM = 'delete_item'
export const INIT_LIST = 'init_list'
export const GET_INIT_LIST = 'get_init_list'